---
title: Waar/onwaar-vlaggen
hero_image: images/banner.png
description: Waar/onwaar-vlaggen gebruiken om te bepalen wanneer code wordt uitgevoerd
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Inleiding
