---
title: Drapeaux vrai/faux
hero_image: images/banner.png
description: Utilise des drapeaux vrai/faux pour contrôler lorsque le code s'exécute
version: 4
listed: false
copyedit: false
last_tested: "2023-09-26"
steps:
  - title: Introduction
